import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from ultrafilter_properties import is_filter

def test_principal_filter():
    X = frozenset([1, 2, 3])
    # Principal filter generated by {1}: all supersets of {1}
    F = {frozenset([1]), frozenset([1, 2]), frozenset([1, 3]), frozenset([1, 2, 3])}
    assert is_filter(F, X)
